### ISSUE TITLE
On every sync: downloads remote notes, doesn't upload local notes, deletes all remote notes.

### ISSUE THREAD

**Issue by mrled** [fletcher/SimplenoteSync#1]
When I run SimplenoteSync,pl, it downloads the remote notes to the local directory just fine, but when it's done, all the notes are gone from the Simplenote web application - it doesn't upload any of my local notes, and it deletes notes that were on the server. 
- My username and password are correct (it's downloading the notes from the server, after all).
- The local directory that I'm specifying in the config file also seems to work (as it's putting the notes in the right directory), and I'm using a full path from / (i.e. not using a "~" character).
- I have Crypt::SSLeay installed (I ran the "perl -MCPAN..." command from the readme, and it did not result in any errors)
- All of my notes are .txt files ("ls *.txt" returns dozens of notes)
- I have been having this problem since I first tried to use SimplenoteSync on Friday, and I just checked out the latest from git, and the problem is still manifest. 

Thanks for any help

**Comment by fletcher** [comment]
I added a debug utility.  Run this and send me the "SimplenoteSyncLog.txt" from your home directory.  Even better is to also run "SimplenoteSync > SimplenoteSyncDebug.txt" with debug mode turned on and send me that file as well.  Can send both files by email to owner@fletcherpenney.net.

This will show me the titles of notes that you have, but not password or email address.  If your titles are confidential, you should delete those particular notes or trim those sections from the log files before sending them to me.

**Comment by fletcher** [comment]
Finally tracked this down, and yes the debug utility helped me do it.  Long story short - glob command sucks, in this case actually needed a space in directory names to make sync work.

Should be fixed now.  So update, backup your data, and give it another go.

Thanks to all who sent in the debug info.
