### ISSUE TITLE
Non-OSX: stat -f needs conditional

### ISSUE THREAD

**Issue by harpchad** [fletcher/SimplenoteSync#4]
Here stat is wrapped by a conditional

198   if ($os =~ /darwin/i) {
199     # The following works on Mac OS X - need a "birth time", not ctime
200     @d = gmtime (readpipe ("stat -f \"%B\" \"$filepath\""));  # created time
201   } else {
202     # TODO: Need a better way to do this on non Mac systems
203     @d = gmtime ((stat("$filepath"))[9]); # get file's modification time
204   }

but it's naked (and broken on linux) here, line 417:

412   foreach my $filepath (glob("$glob_directory/*.txt")) {
413     $filepath = abs_path($filepath);
414     my @d=gmtime ((stat("$filepath"))[9]);
415     $file{$filepath}{modify} = sprintf "%4d-%02d-%02d %02d:%02d:%02d", $d[5]+1900,$d[4]+1,$d[3],$d[2],$d[1],$d[0];
416
417     @d = gmtime (readpipe ("stat -f \"%B\" \"$filepath\""));
418     $file{$filepath}{create} = sprintf "%4d-%02d-%02d %02d:%02d:%02d", $d[5]+1900,$d[4]+1,$d[3],$d[2],$d[1],$d[0];
419   }

**Comment by ndw** [comment]
Yes, I just bumped into this one myself. Even on an OS X box, if you've installed the GNU coreutils (e.g., from MacPorts) this may be an issue.

**Comment by fletcher** [comment]
I think I fixed this.  Still doesn't get the right time, but shouldn't crash.  I think.  Please test and let me know.

**Comment by fletcher** [comment]
It appears to be working per reports from another user.  Thanks!
